### ISSUE TITLE
grub changes needed for ubuntu 18.04

### ISSUE THREAD

**Issue by okvittem** [naftulikay/thinkpad-yoga-3rd-gen-acpi#3]
Hi,
Thanks for the nice wrap up of the iasl stuff.
However I had to also do the grub steps from  the referred javanna recipe.
In my ubuntu 18.04 that also had to be changed to  to include the top dir too /boot :
   initrd /boot/acpi_override ...

Cheers
  Olav

**Comment by naftulikay** [comment]
Interesting. Since the guide I have here has you compile the changes directly into the initramfs, I didn't need to mess with GRUB at all. I actually don't use GRUB, I use [rEFInd](https://www.rodsbooks.com/refind/).

Did you try baking it in using the instructions provided?

**Comment by okvittem** [comment]
Yes, I (think I) followed your instructions, and checked that dsdt did not change.
I changed grub config back and removed the  'initrd /boot/acpi_override' from boot/grub and did not get S3.

So   /etc/initramfs-tools/hooks/acpi_override  probably did not fire or had an error ?
Any way I can debug that  ?

(Anyway my laptop lost only 3% battery during night :-)

**Comment by naftulikay** [comment]
Did you rebuild the initramfs?

Make sure that permissions are 0755 (or at least 0700) on the hook so it'll be seen as executable. You can also add `echo` statements to it to see if it's being completed as part of the initramfs build. You'll see the output if the hook is called.

**Comment by naftulikay** [comment]
Closing because I didn't hear back. Please re-open if you weren't able to get it injected into the initramfs.
